version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: cd selenium_advanced/herokuapp/ && python TestSuites/testsuite_html_report.py
workflows:
  main:
    jobs:
      - build-and-test
